### ISSUE TITLE
Using test-coin dependency fails

### ISSUE THREAD

**Issue by metaclips** [pontem-network/test-coins#5]
Running the let-swap example https://docs.liquidswap.com/integration/lets-swap fails with `"Error": "Unexpected error: Unable to resolve packages for package 'test_swap'"` when I add test-coins dependency
```toml
[package]
name = 'test_swap'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
subdir = 'liquidswap_router_v2/'
rev = 'main'

[dependencies.LiquidswapLP]
git = 'https://github.com/pontem-network/liquidswap.git'
subdir = 'liquidswap_lp/'
rev = 'main'

[dependencies.TestCoins]
git = 'https://github.com/pontem-network/test-coins.git'
rev = 'main'

[addresses]
account = "0x7eedadaefc6cd9a344f5175bb10a6a4ea20399a1391ea7ffa40fd5ef600f8c71"
```
Looking at the `aptos-framework` commit used in test-coin `985f19d40457a5f09f2d741b1feca6bf7ba1f8a6`, it differs with that used in [LiquidSwap](https://github.com/pontem-network/liquidswap/blob/b89aed9adb96c0b083134765f75be814418be670/Move.toml#L33) not sure if this could be the reason or if I'm just doing it wrong. I'm fairly new with the Move language.
